# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbelt', '0002_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite', models.ManyToManyField(related_name='favorites', to='blackbelt.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackbelt.User')),
            ],
        ),
    ]
